In [1]:
import pandas as pd
import numpy as np

In [2]:
load_data = pd.read_csv('Absenteeism_preprocessed_scaled.csv')

In [3]:
load_data.head()

Reason Type 1  Reason Type 2  Reason Type 3  Reason Type 4  Month Value  \
0              0              0              0              1     0.182726   
1              0              0              0              0     0.182726   
2              0              0              0              1     0.182726   
3              1              0              0              0     0.182726   
4              0              0              0              1     0.182726   

   Day of Week  Transportation Expense  Distance to Work       Age  \
0    -0.683704                1.005844          0.412816 -0.536062   
1    -0.683704               -1.574681         -1.141882  2.130803   
2    -0.007725               -0.654143          1.426749  0.248310   
3     0.668253                0.854936         -1.682647  0.405184   
4     0.668253                1.005844          0.412816 -0.536062   

   Daily Work Load Average  Body Mass Index  Education  Children      Pets  \
0                -0.806331         0.767431          0  0.880469  0.268487   
1                -0.806331         1.002633          0 -0.019280 -0.589690   
2                -0.806331         1.002633          0 -0.919030 -0.589690   
3                -0.806331        -0.643782          0  0.880469 -0.589690   
4                -0.806331         0.767431          0  0.880469  0.268487   

   Absenteeism Time in Hours  
0                          4  
1                          0  
2                          2  
3                          4  
4                          2

### Create Targets and Inputs for the Logistic Regression

In [34]:
data_preprocessed = load_data.copy()

In [35]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>
                                                          data_preprocessed['Absenteeism Time in Hours'].median(), 1,0)

In [36]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [37]:
data_preprocessed['Excessive Absence'] = targets

In [38]:
data_preprocessed.drop(['Absenteeism Time in Hours','Day of Week','Daily Work Load Average', 'Distance to Work'], axis=1, inplace = True)

In [39]:
data_preprocessed.head()

Reason Type 1  Reason Type 2  Reason Type 3  Reason Type 4  Month Value  \
0              0              0              0              1     0.182726   
1              0              0              0              0     0.182726   
2              0              0              0              1     0.182726   
3              1              0              0              0     0.182726   
4              0              0              0              1     0.182726   

   Transportation Expense       Age  Body Mass Index  Education  Children  \
0                1.005844 -0.536062         0.767431          0  0.880469   
1               -1.574681  2.130803         1.002633          0 -0.019280   
2               -0.654143  0.248310         1.002633          0 -0.919030   
3                0.854936  0.405184        -0.643782          0  0.880469   
4                1.005844 -0.536062         0.767431          0  0.880469   

       Pets  Excessive Absence  
0  0.268487                  1  
1 -0.589690                  0  
2 -0.589690                  0  
3 -0.589690                  1  
4  0.268487                  0

In [40]:
inputs = data_preprocessed.iloc[:,:-1]
targets = data_preprocessed['Excessive Absence']

### Train Test split

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
X_train, X_test, y_train, y_test = train_test_split(inputs,targets,train_size=0.8, shuffle=True, random_state = 20)

In [43]:
print(X_train.shape, y_train.shape)

(560, 11) (560,)


In [44]:
print(X_test.shape, y_test.shape)

(140, 11) (140,)


### Logistic Regression 

In [45]:
from sklearn.linear_model import LogisticRegression

In [46]:
model = LogisticRegression()

In [47]:
model.fit(X_train, y_train)

LogisticRegression()

In [48]:
from sklearn import metrics

In [49]:
model.score(X_train,y_train)

0.7732142857142857

### Manually checking the Accuracy

In [50]:
model_outputs = model.predict(X_train)

In [51]:
model_outputs == y_train

346     True
91      True
299     True
129     True
695     True
       ...  
218     True
223    False
271     True
474    False
355     True
Name: Excessive Absence, Length: 560, dtype: bool

In [52]:
total_true_entries = np.sum((model_outputs==y_train))
print(total_true_entries)

433


In [53]:
Accuracy = total_true_entries/model_outputs.shape[0]
print(Accuracy)

0.7732142857142857


### Finding the intercept and the coefficients

In [54]:
model.intercept_

array([-1.6474549])

In [55]:
model.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [56]:
feature_names = inputs.columns.values

In [57]:
summary_table = pd.DataFrame(columns = ['Feature'], data = feature_names)
summary_table['Coefficient'] = np.transpose(model.coef_)

In [58]:
summary_table

Feature  Coefficient
0            Reason Type 1     2.800197
1            Reason Type 2     0.951884
2            Reason Type 3     3.115553
3            Reason Type 4     0.839001
4              Month Value     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [59]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] =['Intercept', model.intercept_[0]]
summary_table = summary_table.sort_index()

In [60]:
summary_table

Feature  Coefficient
0                Intercept    -1.647455
1            Reason Type 1     2.800197
2            Reason Type 2     0.951884
3            Reason Type 3     3.115553
4            Reason Type 4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

### Interpreting the Coefficients

In [61]:
summary_table['Odds Ratio'] = np.exp(summary_table.Coefficient)

In [62]:
summary_table

Feature  Coefficient  Odds Ratio
0                Intercept    -1.647455    0.192539
1            Reason Type 1     2.800197   16.447892
2            Reason Type 2     0.951884    2.590585
3            Reason Type 3     3.115553   22.545903
4            Reason Type 4     0.839001    2.314054
5              Month Value     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [63]:
summary_table.sort_values('Odds Ratio', ascending=False)

Feature  Coefficient  Odds Ratio
3            Reason Type 3     3.115553   22.545903
1            Reason Type 1     2.800197   16.447892
2            Reason Type 2     0.951884    2.590585
4            Reason Type 4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

### Backward Elimination

The columns, `Day of Week`, `Daily Work Load Average` and `Distance to Work` are removed later because there coefficients were nearly zero and had negligible effect on the regression.

### Testing the Model

In [64]:
model.score(X_test,y_test)

0.75

#### Getting the probability of an output being `0` or `1` using sklearn

In [65]:
predicted_proba = model.predict_proba(X_test)
predicted_proba

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [66]:
predicted_proba.shape

(140, 2)

In [67]:
predicted_proba[:,1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

### Next Steps:-

1. Save the model.
2. Create a module.
3. Get new data, classify it, pass it through SQL, and analyze it in Tableau.

### Saving the model

In [68]:
 import pickle

In [69]:
with open('model', 'wb') as file:
    pickle.dump(model, file)